### ISSUE TITLE
Still active

### ISSUE THREAD

**Issue by TheBinaryLoop** [CrystalNET-org/helm-paperless-ngx#45]
Hey @psych0d0g,

is this repo still active? If so are there any plans to update paperless-ngx to the current version v2.11.1?

**Comment by saip92** [comment]
+1 Looks like the website of the org owner is down too.

FYI that we can set `image.tag` to override the version and use the container that we want.

**Comment by psych0d0g** [comment]
i am currently a bit limited on time and prioritizing stuff, 
i started a new job recently and am currently refactoring alot of stuff in my personal homelab,
there will be updates again in the future since i am using paperless myself, i just cannot tell you guys a timeframe for that to happen, im afraid

**Comment by psych0d0g** [comment]
updated the chart to latest versions, could you test the last release?

**Comment by TheBinaryLoop** [comment]
I don't run the helm chart anymore but I'm currently experimenting with the ftp docker. I still get an error when trying to execute the paperless_auth binary
![image](https://github.com/user-attachments/assets/f07d9168-9475-40f0-8c96-5ce5f9db4688)

**Comment by psych0d0g** [comment]
should be fixed with docker release https://github.com/CrystalNET-org/paperless-ftpd/releases/tag/0.2.5
